name: PR Pipeline
on:
  pull_request:
    branches:
      - main

jobs:
  pipeline:
    strategy:
      matrix:
        os: ['ubuntu-slim']
        node_version: ['24.13.1']
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}
          check-latest: false
      - name: Checkout repository code
        uses: actions/checkout@v4
      - name: Install PNPM
        run: npm install --global pnpm@10.29.3
      - name: Install dependencies
        run: pnpm install
      - name: Check Typings
        run: pnpm run type:check
      - name: Run lint
        run: pnpm run lint
      - name: Run test
        run: pnpm run test:ci
